### ISSUE TITLE
Multiple endpoint in same ain file

### ISSUE THREAD

**Issue by mikhi-nde** [jonaslu/ain#15]
Hi. hope you are fine. :)

Is there a way to run the same query on multiple endpoint for example:

curl -XDELETE http://elastisearch.local/index_1
curl -XDELETE http://elastisearch.local/index_2
curl -XDELETE http://elastisearch.local/index_3

btw. thank you for this awesome tool.

**Comment by jonaslu** [comment]
A week without any interaction means closing. Re-open if you're still interested.

**Comment by mikhi-nde** [comment]
Hello @jonaslu 

I was busy lately.

I mean having several urls in the same file, in the [host] section

**Comment by jonaslu** [comment]
No problems...

The focus of ain is one URL per invocation. The problem with serveral URLs in the same file is when you combine that file with more files - it then becomes complex how to build the entire url.

Example:
```base.ain

It's fairly easy to script around, in your specific case you could do something like:
