### ISSUE TITLE
Do you plan to support grpc?

### ISSUE THREAD

**Issue by YumaFuu** [jonaslu/ain#27]
I wanna use https://github.com/fullstorydev/grpcurl via ain!

Is it possible to support? I wanna contribute

**Comment by jonaslu** [comment]
Hi! Ain aims to do HTTP and to be usable across many systems (hence the support for wget, curl or httpie).
I haven't heard of grpcurl before and I'm not sure GRPC and HTTP are interchangeable. Do all the sections in ain apply to grpcurl?

But it did make me think of possibly supporting backend plugins / extensions to ain.

**Comment by jonaslu** [comment]
Closing due do inactivity
