### ISSUE TITLE
--vars not working as intended

### ISSUE THREAD

**Issue by on3iro** [jonaslu/ain#30]
Hey,

I just started tinkering with ain and really like it, however it seems that the `--vars` flag is currently broken.
Whenever I try to provide it, ain tries to instead read it as a template file:

```bash
ain ./base.ain --vars STUFF=foo

Error: Could not read template file --vars: open --vars: no such file or directory
```

I tried this with the nix version (1.4) from the unstable channel as well as with the homebrew-version 1.5 (I am on an aarch64 darwin system).

**Comment by jonaslu** [comment]
What version (`ain -v`) are you on? --vars hasn't been included in any release yet

**Comment by on3iro** [comment]
> What version (`ain -v`) are you on? --vars hasn't been included in any release yet

As I've written above I tried v1.4 and 1.5 - but I didn't know that it hasn't been released, yet. I just read the README and assumed, that the docs would relate to the latest release :)

On a side note: what does `ain` actually mean. Constantly trying to figure out where the name's coming from, while using it :D

**Comment by jonaslu** [comment]
Sorry, you did write that. Yes, the README mirrors the current state which can be confusing. A dev branch would solve that :thinking: 

The 1.5 and older way was to set them before the ain command itself (assuming you're in a POSIX shell): `STUFF=foo ain ./base.ain`.

Ha, I'll keep that a secret - as the true origin is pretty boring  :) There are small hints of where it came from in the README.

**Comment by on3iro** [comment]
> Sorry, you did write that. Yes, the README mirrors the current state which can be confusing. A dev branch would solve that 🤔
> 
> The 1.5 and older way was to set them before the ain command itself (assuming you're in a POSIX shell): `STUFF=foo ain ./base.ain`.
> 
> Ha, I'll keep that a secret - the true origin is pretty boring 😸 There are small hints of where it came from in the README.

Yeah, I also just prepended the env variables to my command and this works totally fine for now. Just found the syntax with the `--vars` flag a tad nicer. Anyway thanks for your quick reply. Really like ain so far :+1:
