### ISSUE TITLE
Define requests based on existing OpenAPI spec

### ISSUE THREAD

**Issue by chbndrhnns** [jonaslu/ain#6]
That's something that Insomnia does and makes it much faster to define requests. Is it something that is on your roadmap?

**Comment by jonaslu** [comment]
Hi! It's not on the immediate road-map but I haven't looked into how much work it'll be either.

I'll close this, but feel free to post it in the [discussions](https://github.com/jonaslu/ain/discussions) and we'll see if more are interested in this (and possibly get their hands dirty too :).
